### ISSUE TITLE
Authentication Required  

### ISSUE THREAD

**Issue by alexd555** [Esri/nearby-android#73]
When I press on "retrieving rout" then I get  Authentication Required .

What and Where configure it ?
Can I disable it ?

**Comment by mikewilburn** [comment]
Hi @alexd555. Routing is a premium service which consumes credits, so this does require logging in.
You can read more about direction capabilities here: https://developers.arcgis.com/features/directions/

Are you inquiring on how to use the app builder's credentials for this purpose so that a user of the app is not presented with this 'Authentication Required' challenge?
